name: 'stock_market_dbt'
version: '1.0.0'
config-version: 2

profile: 'stock_market_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  stock_market_dbt:
    staging:
      +materialized: view
    core:
      +materialized: table